name: Update Elite Tech Jobs

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: 
      - 'advanced-job-fetcher.js'
      - 'companies.json'

jobs:
  update-elite-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Fetch elite tech opportunities
      env:
        JSEARCH_API_KEY: ${{ secrets.JSEARCH_API_KEY }}
      run: node advanced-job-fetcher.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Found changes in README"
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
      
    - name: Commit updated job board
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "elite-jobs-bot@github.com"
        git config --local user.name "Elite Jobs Bot"
        git add README.md
        
        # Get job count from README for commit message
        JOB_COUNT=$(grep -o "Active Positions\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
        COMPANY_COUNT=$(grep -o "Companies\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
        
        git commit -m "🚀 Elite Tech Jobs Update - $(date +'%Y-%m-%d')

        📊 Latest Opportunities Summary:
        • $JOB_COUNT active positions from top tech companies
        • $COMPANY_COUNT elite companies (FAANG, unicorns, startups)  
        • Fresh data from career pages and job boards
        • Comprehensive filtering and deduplication applied
        
        🎯 Categories Updated:
        • Software Engineering (all levels)
        • Machine Learning & AI
        • Data Science & Analytics  
        • Mobile Development (iOS/Android)
        • Frontend/Backend/Full Stack
        • DevOps & Infrastructure
        • Product Management & Design
        
        🏢 Company Types:
        • FAANG+ (Google, Apple, Microsoft, Amazon, Meta, etc.)
        • Unicorn Startups (OpenAI, Stripe, Databricks, etc.)
        • Elite Gaming (Epic, Riot, Unity, Roblox)
        • Top Fintech (Coinbase, Robinhood, Square)
        • Enterprise Leaders (Salesforce, Adobe, Oracle)
        
        🔧 Technical Details:
        • Multi-location job search (SF, NYC, Seattle, Austin, Remote)
        • Experience level categorization (Entry/Mid/Senior)
        • Smart company name normalization
        • Duplicate removal and ranking by company tier
        • Rate limit compliance (1.2s delays between API calls)
        
        Next update: Tomorrow at 9 AM UTC"
        
    - name: Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
    - name: Create job summary
      run: |
        echo "## 🚀 Elite Tech Jobs Update Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
          # Extract stats from README
          JOB_COUNT=$(grep -o "Active Positions\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          COMPANY_COUNT=$(grep -o "Companies\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          FAANG_COUNT=$(grep -o "FAANG+ Jobs\*\*: [0-9]*" README.md | grep -o "[0-9]*" || echo "0")
          
          echo "✅ **Successfully updated job board with fresh opportunities**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📊 Today's Haul:" >> $GITHUB_STEP_SUMMARY  
          echo "- 🎯 **$JOB_COUNT total positions** from elite tech companies" >> $GITHUB_STEP_SUMMARY
          echo "- 🏢 **$COMPANY_COUNT companies** tracked (FAANG, unicorns, startups)" >> $GITHUB_STEP_SUMMARY
          echo "- ⭐ **$FAANG_COUNT FAANG+ jobs** from top-tier companies" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔍 Search Coverage:" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 **Multi-location search**: SF Bay Area, NYC, Seattle, Austin, Remote" >> $GITHUB_STEP_SUMMARY
          echo "- 🎓 **All experience levels**: Entry-level to Senior positions" >> $GITHUB_STEP_SUMMARY
          echo "- 💼 **10+ role categories**: SWE, ML/AI, Data, Mobile, DevOps, Product, Design" >> $GITHUB_STEP_SUMMARY
          echo "- 🏆 **Elite companies only**: FAANG, unicorns, top startups, gaming leaders" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Quality Filters Applied:" >> $GITHUB_STEP_SUMMARY
          echo "- ✨ Removed duplicates and spam postings" >> $GITHUB_STEP_SUMMARY
          echo "- 🏢 Normalized company names and subsidiaries" >> $GITHUB_STEP_SUMMARY  
          echo "- 📊 Ranked by company tier (FAANG first)" >> $GITHUB_STEP_SUMMARY
          echo "- 🔗 Verified direct application links" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🔄 Next update**: Tomorrow at 9 AM UTC" >> $GITHUB_STEP_SUMMARY
        else
          echo "ℹ️ **No new opportunities found - job board is current**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All tracked companies have been checked for new postings." >> $GITHUB_STEP_SUMMARY
          echo "The existing job listings are still fresh and active." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🔄 Next check**: Tomorrow at 9 AM UTC" >> $GITHUB_STEP_SUMMARY
        fi