name: Update Dream Jobs README

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths: [ 'update-readme.js' ] # Also run when script is updated

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install node-fetch
        
    - name: Update README with latest jobs
      env:
        JSEARCH_API_KEY: ${{ secrets.JSEARCH_API_KEY }}
      run: node update-readme.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Commit updated README
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Dream Jobs Bot"
        git add README.md
        git commit -m "🤖 Update dream jobs - $(date +'%Y-%m-%d %H:%M UTC')

        - Fetched latest positions from top tech companies
        - Updated job counts and statistics  
        - Refreshed company and location filters
        - Auto-generated by GitHub Actions"
        
    - name: Push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
    - name: Create summary
      run: |
        echo "## 🚀 Dream Jobs Update Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.verify-changed-files.outputs.changed }}" == "true" ]; then
          echo "✅ **README updated with fresh job listings**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- 🔍 Searched 5 job categories across major platforms" >> $GITHUB_STEP_SUMMARY
          echo "- 🏢 Filtered for dream companies only" >> $GITHUB_STEP_SUMMARY  
          echo "- 🧹 Removed duplicates and spam" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Updated statistics and filters" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next update**: Tomorrow at 9 AM UTC" >> $GITHUB_STEP_SUMMARY
        else
          echo "ℹ️ **No changes needed - README is already up to date**" >> $GITHUB_STEP_SUMMARY
        fi